apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-app
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: index-app
  template:
    metadata:
      labels:
        app: index-app
    spec:
      containers:
      - name: index-ctn
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:
          limits:
            cpu: "200m"
            memory: "64Mi"